//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFStudio.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBA_TABLE_FOREIGN
    {
        public long KEY_ID { get; set; }
        public string KEY_NM { get; set; }
        public long PARENT_TABLE_ID { get; set; }
        public long CHILD_TABLE_ID { get; set; }
    }
}
