//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFStudio.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBA_CHAT
    {
        public long CHAT_ID { get; set; }
        public long ROOM_ID { get; set; }
        public long SEND_USER_ID { get; set; }
        public string USER_MSG { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
    }
}
