//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFStudio.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBA_PLAN
    {
        public long PLAN_ID { get; set; }
        public long USER_ID { get; set; }
        public string TITLE { get; set; }
        public long VISIBLE_CD { get; set; }
        public long PLAN_CD { get; set; }
        public string DETAILS { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public Nullable<System.DateTime> PLAN_TIME { get; set; }
    }
}
