//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFStudio.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBA_CHATROOM
    {
        public long ROOM_ID { get; set; }
        public Nullable<long> PROJECT_ID { get; set; }
        public string ROOM_NM { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public long VISIBILITY { get; set; }
    }
}
