//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFStudio.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBA_TICKET
    {
        public long TICKET_ID { get; set; }
        public Nullable<long> PROJECT_ID { get; set; }
        public Nullable<long> TICKET_KBN { get; set; }
        public Nullable<long> PROJECT_KBN { get; set; }
        public string TITLE { get; set; }
        public string DETAIL { get; set; }
        public long FROM_USER_ID { get; set; }
        public Nullable<System.DateTime> FROM_TIME { get; set; }
        public Nullable<long> TO_USER_ID { get; set; }
        public Nullable<long> ANSWER_USER_ID { get; set; }
        public Nullable<long> ANSWER_TIME { get; set; }
        public long STATE { get; set; }
        public Nullable<long> CREATE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<long> UPDATE_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME { get; set; }
        public Nullable<bool> DELETE_FLG { get; set; }
        public Nullable<long> DELETE_ID { get; set; }
        public Nullable<System.DateTime> DELETE_TIME { get; set; }
    }
}
