//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFStudio.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBA_COLUMN
    {
        public long COLUMN_ID { get; set; }
        public string VERSION { get; set; }
        public long TABLE_ID { get; set; }
        public string COLUMN_NM { get; set; }
        public string TYPE_NM { get; set; }
        public string POPULAR_NM { get; set; }
        public string COMMENT { get; set; }
        public long SORT_NO { get; set; }
        public bool PKEY_FLG { get; set; }
        public bool INDEX_FLG { get; set; }
    }
}
