//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFStudio.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBA_TODO
    {
        public long TODO_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<long> PROJECT_ID { get; set; }
        public string TITLE { get; set; }
        public string DETAIL { get; set; }
        public long STAGE { get; set; }
    }
}
