//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFStudio.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBManageEntities : DbContext
    {
        public DBManageEntities()
            : base("name=DBManageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DBA_PROJECT> DBA_PROJECT { get; set; }
        public virtual DbSet<DBA_TICKET> DBA_TICKET { get; set; }
        public virtual DbSet<DBA_TODO> DBA_TODO { get; set; }
        public virtual DbSet<MST_CODE> MST_CODE { get; set; }
        public virtual DbSet<MST_CODEKBN> MST_CODEKBN { get; set; }
        public virtual DbSet<MST_MENU> MST_MENU { get; set; }
        public virtual DbSet<MST_USER> MST_USER { get; set; }
        public virtual DbSet<V_CODELIST> V_CODELIST { get; set; }
        public virtual DbSet<V_TICKETLIST> V_TICKETLIST { get; set; }
        public virtual DbSet<V_TODOLIST> V_TODOLIST { get; set; }
    }
}
