//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFStudio.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_CODE
    {
        public long CODE_ID { get; set; }
        public long CODEKBN_ID { get; set; }
        public string CODE_NM { get; set; }
        public string CODE_NMS { get; set; }
        public bool UNDISPLAY_FLG { get; set; }
    
        public virtual MST_CODEKBN MST_CODEKBN { get; set; }
    }
}
