//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFStudio.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_DATABASE_TYPE
    {
        public long DATABASE_ID { get; set; }
        public string VERSION { get; set; }
        public string DATABASE_NM { get; set; }
    }
}
