//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFStudio.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MST_MENU()
        {
            this.MST_MENU1 = new HashSet<MST_MENU>();
        }
    
        public long MENU_ID { get; set; }
        public Nullable<long> PMENU_ID { get; set; }
        public string NAME { get; set; }
        public string ACTION { get; set; }
        public string CONTROLLER { get; set; }
        public long SORT_NO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_MENU> MST_MENU1 { get; set; }
        public virtual MST_MENU MST_MENU2 { get; set; }
    }
}
