//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFStudio.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_USER
    {
        public long USER_ID { get; set; }
        public string LOGIN_ID { get; set; }
        public string PASSWORD { get; set; }
        public string LOGIN_NM { get; set; }
        public bool LOCKOUT_FLG { get; set; }
        public long LOCKOUT_CNT { get; set; }
        public Nullable<System.DateTime> LOCKOUT_TIME { get; set; }
    }
}
