//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFStudio.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CODELIST
    {
        public long CODEKBN_ID { get; set; }
        public string KBN_NM { get; set; }
        public string KBN_NMS { get; set; }
        public bool K_UNDISP { get; set; }
        public string K_COMMENT { get; set; }
        public long CODE_ID { get; set; }
        public string CODE_NM { get; set; }
        public string CODE_NMS { get; set; }
        public bool C_UNDISP { get; set; }
        public string C_COMMENT { get; set; }
        public long SORT_NO { get; set; }
    }
}
